### ISSUE TITLE
bodyparser middleware missing

### ISSUE THREAD

**Issue by femanso** [ezypeeze/nuxt-neo#1]
Hi! I was trying out your module, but the createAction wasn't working, body was undefined. 
So I installed express-bodyparser and added it to the middleware list, now it works.
Am I missing something or we should take care of our own parsers?

**Comment by ezypeeze** [comment]
Good point, I always used a body parser middleware, so I never really found this issue, i guess I can add this in the module configuration and support multiple encode types (or custom parsing)

**Comment by ezypeeze** [comment]
Added 'bodyParsers' module option [(v1.2.0)](https://github.com/ezypeeze/nuxt-neo/releases/tag/v1.2.0)

Thanks for the feedback :)
