### ISSUE TITLE
Promise.catch() in plugins.api.template.js

### ISSUE THREAD

**Issue by jbnv** [ezypeeze/nuxt-neo#10]
```
/**
 * Runs possible error handler
 *
 * @param error
 * @returns {Function}
 */
function runErrorHandler(error) {
    return ErrorHandler && ErrorHandler(error) || Promise.catch(error);
}
```

`Promise.prototype.catch()` exists. `Promise.catch()` does not. Maybe this is supposed to be Promise.reject(error)?

**Comment by ezypeeze** [comment]
Yep, you right, if u want, make a PR. Otherwise I'll fix when I get some free time

**Comment by ezypeeze** [comment]
Fixed: https://github.com/ezypeeze/nuxt-neo/commit/2b7f053bc4c7f6935abb3298f2be69007e3c1a46

Release: v4.1.0
