### ISSUE TITLE
In clientSideApiHandler the object process.env seems empty

### ISSUE THREAD

**Issue by sapyx** [ezypeeze/nuxt-neo#44]
in In clientSideApiHandler the process.env object appears empty. I need to access the environment variables, what can I do?

**Comment by rchl** [comment]
This is not specific to this module but read https://nuxtjs.org/docs/configuration-glossary/configuration-env on how to make those available.

**Comment by sapyx** [comment]
i use .env file and process.env object is populated in controllers, is empty only in clientSideApiHandler
